title: Erica Li  # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am  a current third year industrial engineering student from the University of Toronto, looking for a 4 months summer internship opportunity commencing May 2020. 
  <br><br>
  I am a multilingual Industrial Engineering student at University of Toronto, minoring in Engineering Business and Artificial Intelligence. My vision lies in integrating technology with financial operation optimization, which lead me to pursue business & AI minor in addition to my engineering major. I am a passionate, dedicated and results-oriented person who has always wished to work in a dynamic environment and improve complex real-world systems.
  I am an excellent team player who strives in team communication and willing to contribute extraeffort for the better outcome. I am also a fast learner who thrives contributing in a fast-paced environment. Last but not least, I enjoy facing complex challenges, working under pressure and taking up responsibilities because they are sources of my motivation to strive for excellence.
  I am open to discuss any potential full time/part time opportunity starting in summer 2020 in any industry.  
  <br><br>
  <a href="https://www.linkedin.com/in/erica-jiawen-li-898851118/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
