title: Erica Li  # your name (or website title) here

<meta property='og:image' content="images/cover_page.png"/>

logo: "/images/1.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I am a current third year Industrial Engineering student at University of Toronto, minoring in Engineering Business and Artificial Intelligence. My vision lies in integrating technology with financial operation optimization, which lead me to pursue business & AI minor in addition to my engineering major. 
  <br><br>
  I am a passionate, dedicated and results-oriented person who has always wished to work in a dynamic environment and improve complex real-world systems.
  I am open to discuss any potential full time/part time opportunity starting in summer 2020 in any industry.  
  <br><br>
  <a href="https://www.linkedin.com/in/erica-jiawen-li-898851118/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
